'use strict';
const $=id=>document.getElementById(id), safe=x=>String(x).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
let active=null,records=[],counter=0;
try{const saved=JSON.parse(localStorage.getItem('sowflow-demo-v1')||'null');if(saved){records=saved.records||[];counter=saved.counter||0;active=records.at(-1)||null;}}catch{}
const fieldDefs=[['project','Project name'],['pmName','PM name'],['pmEmail','PM email','email'],['vendor','Vendor organization'],['vendorContact','Vendor focal point'],['vendorEmail','Vendor focal point email','email'],['customer','Customer organization'],['customerContact','Customer focal point'],['customerEmail','Customer focal point email','email'],['start','Project start date','date'],['end','Project end date','date'],['requirements','Requirements','textarea'],['scope','Scope and deliverables / exclusions','textarea'],['quantity','Quantity / effort (e.g. hours or units)'],['amount','Total amount','number'],['currency','Currency','select'],['milestones','Milestones — dates, deliverables and timelines','textarea'],['success','Success / acceptance criteria','textarea'],['dependencies','External vendors, hardware and software details','textarea'],['travel','Travel details / estimated expenses','textarea']];
const optionalDefs=[['introduction','Engagement summary'],['background','Background / business context'],['objectives','Intended outcomes'],['priceNotes','Taxes, expenses and price assumptions'],['paymentSchedule','Milestone payment basis'],['standards','Delivery standards'],['environment','Working environment'],['reporting','Progress reporting and frequency'],['controls','Oversight / escalation procedures'],['ipTerms','Agreed intellectual property terms'],['contractContact','Contract administration / invoice contact'],['customerObligations','Customer responsibilities'],['vendorObligations','Vendor responsibilities'],['location','Work and delivery location'],['language','Working language'],['specialRequirements','Permits / special conditions'],['security','Information safeguards'],['insurance','Insurance arrangements'],['resources','Staffing / expertise'],['documents','Supporting document references']];
const baseCount=fieldDefs.length;fieldDefs.push(...optionalDefs.map(([k,l])=>[k,l,'textarea']));
$('optional-fields').innerHTML=optionalDefs.map(([k,l])=>'<label>'+l+' (optional)<textarea id="f-'+k+'" rows="2"></textarea></label>').join('');
$('fields').innerHTML=fieldDefs.slice(0,baseCount).map(([key,label,type])=>'<label class="'+(type==='textarea'?'wide':'')+'">'+label+(key==='dependencies'?' (required if a risk flag is selected)':' *')+(type==='textarea'?'<textarea id="f-'+key+'" rows="3"></textarea>':type==='select'?'<select id="f-'+key+'"><option>CAD</option><option>USD</option><option>EUR</option><option>GBP</option></select>':'<input id="f-'+key+'" type="'+(type||'text')+'" '+(type==='number'?'min="0.01" step="0.01"':'')+'>')+'</label>').join('');
function persist(){try{localStorage.setItem('sowflow-demo-v1',JSON.stringify({counter,records}));$('storage').textContent='Saved in this browser. Use synthetic information only.';}catch{$('storage').textContent='Browser storage unavailable. State lasts until you close or refresh this page; export your register.';}}
function data(){const d={};for(const [k] of fieldDefs)d[k]=k==='amount'?Number($('f-'+k).value):$('f-'+k).value;for(const k of ['thirdParty','additionalVendor','hardware','software'])d[k]=$(k).checked;d.travelRequired=$('travelRequired').value==='yes';return d;}
function fill(d){$('travelRequired').value=d.travelRequired?'yes':'no';for(const [k] of fieldDefs)$('f-'+k).value=d[k]??'';for(const k of ['thirdParty','additionalVendor','hardware','software'])$(k).checked=!!d[k];routing();}
function routing(){try{$('route-preview').textContent=SOW.route(data()).join(' → ');}catch{$('route-preview').textContent='Enter a positive amount to see the approval route.';}}
function action(fn){try{fn();$('error').textContent='';persist();render();}catch(e){$('error').textContent=e.message;}}
function download(content,name,type){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(){const s=active;$('register').innerHTML=records.map((r,i)=>'<tr><td><button class="quiet" data-record="'+i+'">'+safe(r.id)+'</button></td><td>'+safe(r.data.project)+'</td><td>r'+r.revision+'</td><td>'+safe(r.state)+'</td><td>'+safe(r.state==='Pending approval'?r.route[r.step]:'—')+'</td></tr>').join('');for(const b of document.querySelectorAll('[data-record]'))b.onclick=()=>{active=records[Number(b.dataset.record)];fill(active.data);render();};$('workspace').hidden=!s;if(!s)return;$('status').textContent=s.id+' · Revision '+s.revision+' · '+s.state;$('doc-preview').innerHTML=SOW.preview(s);$('word').textContent=s.state==='Fully approved'?'Download final PDF (.pdf)':'Download draft Word (.docx)';$('review').disabled=s.state!=='PM review'||s.reviewed;$('submit').disabled=s.state!=='PM review'||!s.reviewed;$('revise').disabled=!['PM review','Rejected'].includes(s.state);$('approve').disabled=s.state!=='Pending approval';$('reject').disabled=s.state!=='Pending approval';$('next').textContent=s.state==='Pending approval'?'Acting as: '+s.route[s.step]+' (simulation)':s.state==='Fully approved'?'Internal approvals complete. Signatures are still required.':s.state==='Rejected'?'Revise the form, save a revision, review, and resubmit.':'PM review is required before submission.';$('steps').innerHTML=s.route.map((r,i)=>'<li class="'+(s.state==='Pending approval'&&i===s.step?'current':'')+'">'+safe(r)+(s.state==='Pending approval'||s.state==='Fully approved'?i<s.step?' — approved':i===s.step?' — awaiting':' — queued':' — '+(s.state==='Rejected'?'restart required':'not submitted'))+'</li>').join('');$('emails').innerHTML=s.emails.slice().reverse().map(e=>'<article><b>'+safe(e.subject)+'</b><p>To: '+safe(e.to)+'</p><p>'+safe(e.body)+'</p><small>'+safe(e.time)+' · Attempt '+e.attempt+'</small></article>').join('')||'<p>No notifications yet.</p>';$('history').textContent=s.history.map(e=>e.time+' | r'+e.revision+' | attempt '+e.attempt+' | '+e.text).join('\n')||'Generated SOW awaiting PM review.';}
$('form').oninput=routing;
$('sample').onclick=()=>fill(SAMPLE);
$('generate').onclick=()=>action(()=>{const s=SOW.create(data(),counter+1);counter++;records.push(s);active=s;});
$('revise').onclick=()=>action(()=>SOW.revise(active,data()));
$('review').onclick=()=>action(()=>SOW.review(active));
$('submit').onclick=()=>action(()=>SOW.submit(active));
$('approve').onclick=async()=>{action(()=>{SOW.decide(active,active.route[active.step],true,$('comment').value);$('comment').value='';});if(active.state==='Fully approved')await finalPDF();};
$('reject').onclick=()=>action(()=>{SOW.decide(active,active.route[active.step],false,$('comment').value);$('comment').value='';});
async function finalPDF(){const s=active;try{const bytes=await SOWPDF.pdf(s);download(bytes,s.id+'-r'+s.revision+'-approved.pdf','application/pdf');$('error').textContent='';}catch(e){$('error').textContent='PDF export: '+e.message;}}
$('word').onclick=async()=>{if(active.state==='Fully approved')await finalPDF();else download(SOW.docx(active),active.id+'-r'+active.revision+'.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document');};
$('export').onclick=()=>download(JSON.stringify({records,counter},null,2),'sowflow-register.json','application/json');
fill(active?active.data:SAMPLE);render();
